[project]
name = "snake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "numpy>=2.2.6",
    "pygame>=2.6.1",
    "torch>=2.9.1",
]
